---
# Default variables for PostgreSQL role

postgresql_service_name: "postgresql"
postgresql_group: "postgres"
neurondb_database_name: "neurondb"
neurondb_database_user: "neurondb"

# Paths will be set based on OS
postgresql_bin_dir: "/usr/bin"
postgresql_config_dir: "/etc/postgresql/{{ postgresql_version }}/main"
postgresql_data_dir: "/var/lib/postgresql/{{ postgresql_version }}/main"

