---
# Handlers for NeuronDesktop role

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart neurondesktop
  systemd:
    name: "{{ item }}"
    state: restarted
  loop:
    - neurondesk-api
    - neurondesk-frontend

