{{- if .Values.neurondb.postgresql.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "neurondb.fullname" . }}-postgres-config
  labels:
    {{- include "neurondb.neurondb.labels" . | nindent 4 }}
data:
  postgresql.conf: |
{{- .Values.neurondb.postgresql.config | indent 4 }}
{{- end }}

