{{- if and .Values.monitoring.enabled .Values.monitoring.grafana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "neurondb.fullname" . }}-grafana
  labels:
    {{- include "neurondb.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "neurondb.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
{{- end }}

