{{- if and .Values.monitoring.enabled .Values.monitoring.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "neurondb.fullname" . }}-prometheus
  labels:
    {{- include "neurondb.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "neurondb.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
{{- end }}

