{{- if and .Values.monitoring.enabled .Values.monitoring.prometheus.enabled .Values.monitoring.prometheus.alertmanager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "neurondb.fullname" . }}-alertmanager
  labels:
    {{- include "neurondb.labels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
spec:
  type: {{ .Values.monitoring.prometheus.alertmanager.service.type }}
  ports:
    - port: {{ .Values.monitoring.prometheus.alertmanager.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "neurondb.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
{{- end }}






