{{- if and .Values.neurondb.enabled .Values.neurondb.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "neurondb.fullname" . }}-neurondb
  labels:
    {{- include "neurondb.neurondb.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.neurondb.podDisruptionBudget.minAvailable | default 1 }}
  selector:
    matchLabels:
      {{- include "neurondb.neurondb.selectorLabels" . | nindent 6 }}
{{- end }}

