{{- if .Values.neuronagent.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "neurondb.neuronagent.serviceName" . }}
  labels:
    {{- include "neurondb.neuronagent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.neuronagent.service.type }}
  ports:
    - port: {{ .Values.neuronagent.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "neurondb.neuronagent.selectorLabels" . | nindent 4 }}
{{- end }}

