{{- if .Values.neurondesktop.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "neurondb.neurondesktop-frontend.serviceName" . }}
  labels:
    {{- include "neurondb.neurondesktop-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.neurondesktop.frontend.service.type }}
  ports:
    - port: {{ .Values.neurondesktop.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "neurondb.neurondesktop-frontend.selectorLabels" . | nindent 4 }}
{{- end }}

