{{- if .Values.neurondb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "neurondb.neurondb.serviceName" . }}
  labels:
    {{- include "neurondb.neurondb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.neurondb.service.type }}
  ports:
    - port: {{ .Values.neurondb.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "neurondb.neurondb.selectorLabels" . | nindent 4 }}
{{- end }}

