{{- if .Values.neurondesktop.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "neurondb.neurondesktop-api.serviceName" . }}
  labels:
    {{- include "neurondb.neurondesktop-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.neurondesktop.api.service.type }}
  ports:
    - port: {{ .Values.neurondesktop.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "neurondb.neurondesktop-api.selectorLabels" . | nindent 4 }}
{{- end }}

