apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: neurondb

resources:
  - namespace.yaml
  - helmrelease.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/values/postgresql/external/secretName
        value: neurondb-external-postgres-secret
    target:
      kind: HelmRelease
      name: neurondb

